services:
  - type: web
    name: fomotron-bot
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    branch: main
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Set manually in Render dashboard
      - key: TELEGRAM_CHAT_ID
        sync: false  # Set manually in Render dashboard
      - key: PORT
        value: 10000
